### ISSUE TITLE
Photo Printer Class

### ISSUE THREAD

**Issue by bmpenn** [pgossman/plogger#1]
Need a classification for printers that take more than 4 cartriges.  Such as the epson stylus pro 9900 or 4900.  Could it be possible when creating the printer model if you select a 3rd option "photo" that allows you to set the number of needed cartdriges...  Just brainstorming ideas.  Hope everything is going well for you.

**Comment by pgossman** [comment]
Just to keep you updated, I have been actively working on this issue and am expecting a solution to be ready within 1-2 days. I will give you an update script for the web pages and a script for the database schema changes once completed.

I will test the update scripts against the original version which you are on to ensure that the update goes smoothly.

Thanks for the suggestion!

**Comment by pgossman** [comment]
This feature has been implemented and is present on the master branch. Closing the issue.
